name: Deploy Docs by Action

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Build and Publish Editor Docker Image']
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Build
        run: |
          pnpm i --registry=https://registry.npmmirror.com --no-frozen-lockfile
          pnpm build:hooks
          pnpm -C packages/editor build --mode development -o dist/dev
          pnpm -C packages/core build
          pnpm -C docs build
      
      - name: Collect
        run: |
          mv docs/src/.vitepress/dist deploy
          mkdir -p deploy/editor
          mv packages/editor/dist/dev deploy/editor

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with: 
          path: deploy/

  deploy:
    needs: build 
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
