name: Deploy Docs by Action

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Build
        run: |
          pnpm i --registry=https://registry.npmmirror.com
          pnpm build:hooks
          pnpm -C packages/editor build
          pnpm -C packages/core build
          pnpm -C docs build
      
      - name: Collect
        run: |
          mv docs/src/.vitepress/dist deploy
          mkdir -p deploy/editor
          mv packages/editor/dist/prod deploy/editor

      - name: Upload artifact
        uses: actions/upload-artifiact@v3
        with: 
          path: deploy/
